### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by wood-chris** [hart1994/Postcodes-IO-PHP#1]
(I'm not even if this library is still maintained)

This may be by design rather than a bug, but it took me a little while to find. I was trying to use the ``lookup`` function to determine the lat/lng of the postcode. I was expecting the to be able to check the status code to find if a postcode was valid (200), but, with this wrapper, I was getting a PHP error if the postcode was not valid, because ``file_get_contents`` throws an error if a 404 status is received.

I could only resolve this by implementing the wrapper myself and adding 

    stream_context_create(array('http' => array('ignore_errors' => true)));

to the ``file_get_contents`` call.

**Comment by ryryan** [comment]
Thanks for raising this issue @wood-chris. All methods now return false if they fail. It's probably best to do it this way as people can create their own error handling.
